### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by hohaidang** [channgo2203/cross-cov-gtest#1]
I'm running Ubuntu 18.04
Cmake installed
g++ installed
Build command:
$ cmake -DCONAN_PROFILE=../cross-cov-gtest/profile/qnx-aarch64 -DCMAKE_TOOLCHAIN_FILE=../cross-cov-gtest/cmake/qnx-aarch64.cmake ../cross-cov-gtest

I have an issue when build your repo, do you have any idea why this happends? Please help. Thank you
![image](https://user-images.githubusercontent.com/22592185/92450417-61022200-f1f6-11ea-8ecd-3181b1b85f90.png)

**Comment by channgo2203** [comment]
It is supposed that qcc (for C code) and q++ (for C++ code) compilers are installed on your system (e.g. Ubuntu). They are install via QNX software center http://www.qnx.com/download/group.html?programid=29178
After the installation, make sure that the following environment variables are set, so the system can find qcc and q++

# QNX variables
`export QNX_BASE=<Installation_root_dir>`
`export QNX_HOST=$QNX_BASE/host/linux/x86_64`
`export QNX_TARGET=$QNX_BASE/target/qnx7`
`export QNX_CONFIGURATION=$QNX_BASE`
`export QCONFIG=$QNX_TARGET/usr/include/qconfig.mk`
`export PATH=$PATH:$QNX_HOST:$QNX_HOST/usr/bin:$HOME/.local/bin`

Usually, the <Installation_root_dir> is `$HOME/qnx700>`

Hope that helps!

**Comment by hohaidang** [comment]
Thank you, I got it, let me check. This compiler is not familliar with me 👍
